import { technology } from "../types/technology";

export const data: technology[] = [
  {
    name: "Node.js",
    src: "logos/nodejs.svg",
    bgColor: "#8CC84B",
    type: "backend",
  },
  {
    name: "Express",
    src: "logos/express.svg",
    bgColor: "#a7a7a7",
    type: "backend",
    darkInvert: true,
  },
  {
    name: "Golang",
    src: "logos/golang.svg",
    bgColor: "#00ADD8",
    type: "backend",
  },
  {
    name: "PostgreSQL",
    src: "logos/postgresql.svg",
    bgColor: "#336791",
    type: "backend",
  },
  {
    name: "MySQL",
    src: "logos/mysql.svg",
    bgColor: "#00758F",
    type: "backend",
  },
  {
    name: "SQLite",
    src: "logos/sqlite.svg",
    bgColor: "#003B57",
    type: "backend",
  },
  {
    name: "Prisma.js",
    src: "logos/prisma.svg",
    bgColor: "#0C344B",
    type: "backend",
    darkInvert: true,
  },
  {
    name: "React.js",
    src: "logos/react.svg",
    bgColor: "#61DAFB",
    type: "frontend",
  },
  {
    name: "Next.js",
    src: "logos/nextjs.svg",
    bgColor: "#a7a7a7",
    type: "frontend",
    darkInvert: true,
  },
  {
    name: "TailwindCSS",
    src: "logos/tailwindcss.svg",
    bgColor: "#38B2AC",
    type: "frontend",
  },
  {
    name: "Styled Components",
    src: "logos/styled-components.svg",
    bgColor: "#DB7093",
    type: "frontend",
  },
  {
    name: "HTML",
    src: "logos/html.svg",
    bgColor: "#E34F26",
    type: "frontend",
  },
  {
    name: "CSS",
    src: "logos/css.svg",
    bgColor: "#1572B6",
    type: "frontend",
  },
  {
    name: "Javascript",
    src: "logos/javascript.svg",
    bgColor: "#F7DF1E",
    type: "frontend",
  },
  {
    name: "Docker",
    src: "logos/docker.svg",
    bgColor: "#2496ED",
    type: "tool",
  },
  {
    name: "Git",
    src: "logos/git.svg",
    bgColor: "#F05032",
    type: "tool",
  },
  {
    name: "Yarn",
    src: "logos/yarn.svg",
    bgColor: "#2C8EBB",
    type: "tool",
  },
  {
    name: "Figma",
    src: "logos/figma.svg",
    bgColor: "#F24E1E",
    type: "tool",
  },
  {
    name: "Vercel",
    src: "logos/vercel.svg",
    bgColor: "#a7a7a7",
    type: "tool",
    darkInvert: true,
  },
  {
    name: "Typescript",
    src: "logos/typescript.svg",
    bgColor: "#3178C6",
    type: "tool",
  },
];
