import { technology } from "../types/technology";

export const technologies: technology[] = [
    // Languages
    {
        name: "C#",
        src: "logos/csharp.svg",
        backgroundColor: "#a179dc26",
        type: "language",
        url: "https://dotnet.microsoft.com/",
        description:
            "A modern, object-oriented programming language used for building applications on the .NET platform.",
    },
    {
        name: "Javascript",
        src: "logos/javascript.svg",
        backgroundColor: "#F7DF1E26",
        type: "language",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        description:
            "The core programming language of the web, used for creating dynamic and interactive user interfaces.",
    },
    {
        name: "Typescript",
        src: "logos/typescript.svg",
        backgroundColor: "#3178C626",
        type: "language",
        url: "https://www.typescriptlang.org/",
        description: "A typed superset of JavaScript that improves developer experience and scalability.",
    },
    {
        name: "Python",
        src: "logos/python.svg",
        backgroundColor: "linear-gradient(135deg, #3776AB26, #FFD43B26)",
        type: "language",
        url: "https://www.python.org/",
        description:
            "A high-level programming language known for readability, automation, backend development, and data science.",
    },
    {
        name: "HTML",
        src: "logos/html.svg",
        backgroundColor: "#E34F2626",
        type: "language",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
        description: "The standard markup language used to structure content on the web.",
    },
    {
        name: "CSS",
        src: "logos/css.svg",
        backgroundColor: "#1572B626",
        type: "language",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
        description: "A stylesheet language used to design and visually style web pages.",
    },

    // Frameworks & Libraries
    {
        name: ".NET",
        src: "logos/dotnet.svg",
        backgroundColor: "#512bd426",
        type: "framework",
        url: "https://dotnet.microsoft.com/",
        description: "A cross-platform framework for building web, desktop, mobile, and cloud applications.",
    },
    {
        name: "React.js",
        src: "logos/react.svg",
        backgroundColor: "#61DAFB26",
        type: "library",
        url: "https://react.dev/",
        description: "A component-based JavaScript library for building user interfaces efficiently.",
    },
    {
        name: "Redux",
        src: "logos/redux.svg",
        backgroundColor: "#7449b926",
        type: "library",
        url: "https://redux.js.org/",
        description: "A predictable state management library commonly used with React applications.",
    },
    {
        name: "Angular",
        src: "logos/angular.svg",
        backgroundColor: "#b52e3126",
        type: "framework",
        url: "https://angular.io/",
        description: "A TypeScript-based framework for building scalable enterprise-level web applications.",
    },
    {
        name: "Next.js",
        src: "logos/nextjs.svg",
        backgroundColor: "#a7a7a726",
        type: "framework",
        darkInvert: true,
        url: "https://nextjs.org/",
        description: "A React framework for building fast, SEO-friendly applications with server-side rendering.",
    },
    {
        name: "Node.js",
        src: "logos/nodejs.svg",
        backgroundColor: "#8CC84B26",
        type: "framework",
        url: "https://nodejs.org/",
        description: "A JavaScript runtime environment for building scalable backend applications.",
    },
    {
        name: "TailwindCSS",
        src: "logos/tailwindcss.svg",
        backgroundColor: "#38B2AC26",
        type: "framework",
        url: "https://tailwindcss.com/",
        description: "A utility-first CSS framework for building modern, responsive interfaces quickly.",
    },
    {
        name: "Express",
        src: "logos/express.svg",
        backgroundColor: "#a7a7a726",
        type: "framework",
        darkInvert: true,
        url: "https://expressjs.com/",
        description: "A minimalist web framework for Node.js used to build APIs and servers.",
    },
    {
        name: "Nest.JS",
        src: "logos/nestjs.svg",
        backgroundColor: "#f5005726",
        type: "framework",
        url: "https://nestjs.com/",
        description: "A progressive Node.js framework for building scalable and maintainable backend applications.",
    },

    // Databases
    {
        name: "SQL Server",
        src: "logos/sqlserver.svg",
        backgroundColor: "#b71d1d26",
        type: "databaseManagementSystem",
        url: "https://www.microsoft.com/sql-server",
        description: "Microsoft’s enterprise-grade relational database system.",
    },
    {
        name: "PostgreSQL",
        src: "logos/postgresql.svg",
        backgroundColor: "#33679126",
        type: "databaseManagementSystem",
        url: "https://www.postgresql.org/",
        description: "A powerful, open-source object-relational database known for reliability and performance.",
    },
    {
        name: "MySQL",
        src: "logos/mysql.svg",
        backgroundColor: "#00758F26",
        type: "databaseManagementSystem",
        url: "https://www.mysql.com/",
        description: "A popular open-source relational database commonly used in web applications.",
    },
    {
        name: "SQLite",
        src: "logos/sqlite.svg",
        backgroundColor: "#003B5726",
        type: "databaseManagementSystem",
        url: "https://www.sqlite.org/",
        description: "A lightweight, file-based SQL database engine ideal for embedded applications.",
    },
    {
        name: "MongoDB",
        src: "logos/mongodb.svg",
        backgroundColor: "#4e9d4b26",
        type: "databaseManagementSystem",
        url: "https://www.mongodb.com/",
        description: "A NoSQL database that stores data in flexible, JSON-like documents.",
    },

    // Tools
    {
        name: "Git",
        src: "logos/git.svg",
        backgroundColor: "#F0503226",
        type: "tool",
        url: "https://git-scm.com/",
        description: "A distributed version control system used to track changes in code.",
    },
    {
        name: "GitHub",
        src: "logos/github.svg",
        backgroundColor: "#a7a7a726",
        type: "tool",
        url: "https://github.com/",
        description: "A cloud-based platform for hosting code repositories and collaborating with developers.",
    },
    {
        name: "Vite",
        src: "logos/vite.svg",
        backgroundColor: "#8e6efe26",
        type: "tool",
        url: "https://vitejs.dev/",
        description: "A fast development build tool with native ES module support.",
    },
    {
        name: "Docker",
        src: "logos/docker.svg",
        backgroundColor: "#2496ED26",
        type: "tool",
        url: "https://www.docker.com/",
        description: "A platform for building and deploying containerized applications.",
    },
    {
        name: "Eslint",
        src: "logos/eslint.svg",
        backgroundColor: "#35459f26",
        type: "tool",
        url: "https://eslint.org/",
        description: "A tool for identifying and fixing problems in JavaScript/TypeScript code.",
    },
    {
        name: "Prettier",
        src: "logos/prettier.svg",
        backgroundColor: "#47414526",
        type: "tool",
        url: "https://prettier.io/",
        description: "An opinionated code formatter that ensures consistent style.",
    },
    {
        name: "Prisma",
        src: "logos/prisma.svg",
        backgroundColor: "#00000026",
        type: "tool",
        darkInvert: true,
        url: "https://www.prisma.io/",
        description: "A modern ORM for Node.js and TypeScript, enabling type-safe database queries.",
    },
    {
        name: "Yarn",
        src: "logos/yarn.svg",
        backgroundColor: "#2C8EBB26",
        type: "tool",
        url: "https://yarnpkg.com/",
        description: "A fast, reliable package manager for JavaScript projects.",
    },
    {
        name: "Figma",
        src: "logos/figma.svg",
        backgroundColor: "linear-gradient(135deg, #F24E1E26, #A259FF26, #0ACF8326, #FF726226, #1ABCFE26)",
        type: "tool",
        url: "https://www.figma.com/",
        description: "A collaborative interface design tool for creating UI/UX prototypes.",
    },
    {
        name: "Vercel",
        src: "logos/vercel.svg",
        backgroundColor: "#00000026",
        type: "tool",
        darkInvert: true,
        url: "https://vercel.com/",
        description: "A cloud platform for deploying front-end applications with ease.",
    },
    {
        name: "xUnit",
        src: "logos/xunit.svg",
        backgroundColor: "#bbbbbb26",
        type: "tool",
        url: "https://xunit.net/",
        description: "xUnit.net is a free, open source, community-focused unit testing tool for C#",
    },
    {
        name: "Jest",
        src: "logos/jest.svg",
        backgroundColor: "#8f3e5526",
        type: "tool",
        url: "https://jestjs.io/",
        description: "A JavaScript testing framework focused on simplicity and speed.",
    },
    {
        name: "Postman",
        src: "logos/postman.svg",
        backgroundColor: "#f3703626",
        type: "tool",
        url: "https://www.postman.com/",
        description: "A platform for building, testing, and debugging APIs.",
    },
];
